### ISSUE TITLE
How to choose certain label in 3d array for meshing?

### ISSUE THREAD

**Issue by thoth291** [nschloe/pygalmesh#101]
Dear PyGalMesh team!
Thank you for this wonderful package! Really grateful for all the effort went to it!

I'm slightly confused by this example: https://github.com/nschloe/pygalmesh#meshes-from-numpy-array-representing-3d-images.
It says that
_The phantom comprises **four** tissue types (background, fat, fibrograndular, skin, vascular tissues). The generated mesh conforms to **tissues** interfaces._

So what if I would like to build a mesh only for **fat** - how would I instruct this interface to do so?
It's fine for me to edit array - I just don't know how.

My current array is uint8 with 3 types - pore space (labeled with 0), material space (labeled with 1) and some fluid (labeled with 2). *How would I create a mesh only for material?*

Excuse me for my luck of knowledge - I'm very new to meshing - was working in different physics all my life - now switching to a new domain.

Thanks in Advance!

**Comment by nschloe** [comment]
I'd just play around with the code in the readme.

**Comment by thoth291** [comment]
@nschloe , what I did is simply something like this (not real code):
```python
vol = (vol==1).astype(np.uint8)
```
And it seems to be doing something, but since I don't know how my mesh should look like in the first place I'm still exploring and testing.

**Comment by flothesof** [comment]
Hi @thoth291 

I've tried to approach your problem from a simpler perspective: by making a simpler double-sphere inside a rectangular volume. 
It has three "materials":
- 0 for "the outside"
- 1 for the inner ROI
- 2 for the outer ROI

Here's the script:
```python
import numpy as np
import pygalmesh

Nx = 72
Ny = 41
Nz = 28
h = [0.2] * 3

vol = np.zeros((Nx, Ny, Nz))
X, Y, Z = np.meshgrid(np.linspace(0, Nx * h[0], num=Nx),
                      np.linspace(0, Ny * h[1], num=Ny),
                      np.linspace(0, Nz * h[2], num=Nz), indexing='ij')

x0, y0, z0 = X.mean(), Y.mean(), Z.mean()

# let's define spherical ROIs
roi_outer = (X-x0)**2 + (Y - y0)**2 + (Z - z0)**2 < 2**2
roi_inner = (X-x0)**2 + (Y - y0)**2 + (Z - z0)**2 < 1

# ... and assign some values to them (in reverse order else it will overwrite the previous values)
vol[roi_outer] = 2
vol[roi_inner] = 1

# and let's make a mesh with it
mesh = pygalmesh.generate_from_array(vol.astype(np.uint8), h, facet_distance=0.2, cell_size=0.5)
mesh.write("spheres_in_square.vtk")
```
Here's the result, visualized with Paraview:
![image](https://user-images.githubusercontent.com/2360669/94144002-e7626900-fe70-11ea-8182-67266e2ddf41.png)

So the implicit convention is that the outer mesh geometry will correspond to class 0. We can test this understanding by initializing the volume with a different value (e.g. 3): `vol = np.zeros((Nx, Ny, Nz)) + 3`.

In that case, the result is:
![image](https://user-images.githubusercontent.com/2360669/94144488-7bcccb80-fe71-11ea-9a9d-820e0f865847.png)

I hope this helps you get started.

Cheers
Florian
