### ISSUE TITLE
polygon soup orientation not checked for volume meshing

### ISSUE THREAD

**Issue by bigfooted** [nschloe/pygalmesh#103]
When a surface mesh is remeshed using remesh-surface, the result is saved without proper orientation. cgal also does this. When loading this surface into a polyhedron instance for volume meshing, the loading fails (In my case always). 

A solution for volume meshing is to read the points and polygons from file separately and then call CGAL::Polygon_mesh_processing::orient_polygon_soup() and CGAL::Polygon_mesh_processing::polygon_soup_to polygon_mesh () when a bad orientation is found, or do it always.

**Comment by nschloe** [comment]
Sure. Can you prepare a PR? Best make it an option, default `False`.

**Comment by bigfooted** [comment]
No problem, I will add an activation switch.

**Comment by nschloe** [comment]
Fixed by #104.
