### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BinWang0213** [nschloe/pygalmesh#12]
System: Ubuntu 14.04
Try to install by following but failed:
sudo apt install libcgal-dev libeigen3-dev (SUCCESS)
pip install -U pygalmesh (FAILED)

Do you have any idea about this?

Complete info:

bwang31@bwang31-PoreSim:~$ pip install -U pygalmesh
Collecting pygalmesh
  Using cached pygalmesh-0.2.2.tar.gz
Requirement already up-to-date: numpy in ./Software/ENTER/lib/python3.6/site-packages (from pygalmesh)
Requirement already up-to-date: pybind11>=2.2 in ./Software/ENTER/lib/python3.6/site-packages (from pygalmesh)
Requirement already up-to-date: pipdate in ./Software/ENTER/lib/python3.6/site-packages (from pygalmesh)
Requirement already up-to-date: requests in ./Software/ENTER/lib/python3.6/site-packages (from pipdate->pygalmesh)
Requirement already up-to-date: appdirs in ./Software/ENTER/lib/python3.6/site-packages (from pipdate->pygalmesh)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in ./Software/ENTER/lib/python3.6/site-packages (from requests->pipdate->pygalmesh)
Requirement already up-to-date: idna<2.7,>=2.5 in ./Software/ENTER/lib/python3.6/site-packages (from requests->pipdate->pygalmesh)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in ./Software/ENTER/lib/python3.6/site-packages (from requests->pipdate->pygalmesh)
Requirement already up-to-date: certifi>=2017.4.17 in ./Software/ENTER/lib/python3.6/site-packages (from requests->pipdate->pygalmesh)
Building wheels for collected packages: pygalmesh
  Running setup.py bdist_wheel for pygalmesh ... error
  Complete output from command /home/bwang31/Software/ENTER/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hijtiy17/pygalmesh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpb0tqrbuhpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pygalmesh
  copying pygalmesh/__about__.py -> build/lib.linux-x86_64-3.6/pygalmesh
  copying pygalmesh/__init__.py -> build/lib.linux-x86_64-3.6/pygalmesh
  running build_ext
  building '_pygalmesh' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -B /home/bwang31/Software/ENTER/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/eigen3/ -I/home/bwang31/Software/ENTER/include/python3.6m -I/home/bwang31/.local/include/python3.6m -I/home/bwang31/Software/ENTER/include/python3.6m -c src/generate.cpp -o build/temp.linux-x86_64-3.6/src/generate.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /usr/include/c++/4.8/array:35:0,
                   from src/domain.hpp:5,
                   from src/generate.hpp:4,
                   from src/generate.cpp:3:
  /usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
   #error This file requires compiler and library support for the \
    ^
  In file included from src/generate.hpp:4:0,
                   from src/generate.cpp:3:
  src/domain.hpp:15:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     virtual ~DomainBase() = default;
                             ^
  src/domain.hpp:19:14: error: ‘array’ in namespace ‘std’ does not name a type
     eval(const std::array<double, 3> & x) const = 0;
                ^
  src/domain.hpp:19:19: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
     eval(const std::array<double, 3> & x) const = 0;
                     ^
  src/domain.hpp:19:24: error: expected ‘,’ or ‘...’ before ‘<’ token
     eval(const std::array<double, 3> & x) const = 0;
                          ^
  src/domain.hpp:26:27: error: ‘array’ is not a member of ‘std’
     std::vector<std::vector<std::array<double, 3>>>
                             ^
  src/domain.hpp:26:27: error: ‘array’ is not a member of ‘std’
  src/domain.hpp:26:49: error: template argument 1 is invalid
     std::vector<std::vector<std::array<double, 3>>>
                                                   ^
  src/domain.hpp:26:49: error: template argument 2 is invalid
  src/domain.hpp:27:18: error: template argument 1 is invalid
     get_features() const
                    ^
  src/domain.hpp:27:18: error: template argument 2 is invalid
  src/domain.hpp:28:3: error: expected unqualified-id before ‘{’ token
     {
     ^
  In file included from /usr/include/CGAL/Uncertain.h:28:0,
                   from /usr/include/CGAL/assertions.h:344,
                   from /usr/include/CGAL/basic.h:42,
                   from /usr/include/CGAL/Cartesian/Cartesian_base.h:28,
                   from /usr/include/CGAL/Simple_cartesian.h:28,
                   from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28,
                   from src/generate.cpp:5:
  /usr/include/c++/4.8/typeinfo:39:37: error: expected ‘}’ before end of line
   #pragma GCC visibility push(default)
                                       ^
  /usr/include/c++/4.8/typeinfo:39:37: error: expected unqualified-id before end of line
  /usr/include/c++/4.8/typeinfo:39:37: error: expected ‘}’ before end of line
  /usr/include/c++/4.8/typeinfo:39:37: error: expected declaration before end of line
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pygalmesh
  Running setup.py clean for pygalmesh
Failed to build pygalmesh
Installing collected packages: pygalmesh
  Running setup.py install for pygalmesh ... error
    Complete output from command /home/bwang31/Software/ENTER/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hijtiy17/pygalmesh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qsf7xh4c-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pygalmesh
    copying pygalmesh/__about__.py -> build/lib.linux-x86_64-3.6/pygalmesh
    copying pygalmesh/__init__.py -> build/lib.linux-x86_64-3.6/pygalmesh
    running build_ext
    building '_pygalmesh' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -B /home/bwang31/Software/ENTER/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/eigen3/ -I/home/bwang31/Software/ENTER/include/python3.6m -I/home/bwang31/.local/include/python3.6m -I/home/bwang31/Software/ENTER/include/python3.6m -c src/generate.cpp -o build/temp.linux-x86_64-3.6/src/generate.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /usr/include/c++/4.8/array:35:0,
                     from src/domain.hpp:5,
                     from src/generate.hpp:4,
                     from src/generate.cpp:3:
    /usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
     #error This file requires compiler and library support for the \
      ^
    In file included from src/generate.hpp:4:0,
                     from src/generate.cpp:3:
    src/domain.hpp:15:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
       virtual ~DomainBase() = default;
                               ^
    src/domain.hpp:19:14: error: ‘array’ in namespace ‘std’ does not name a type
       eval(const std::array<double, 3> & x) const = 0;
                  ^
    src/domain.hpp:19:19: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
       eval(const std::array<double, 3> & x) const = 0;
                       ^
    src/domain.hpp:19:24: error: expected ‘,’ or ‘...’ before ‘<’ token
       eval(const std::array<double, 3> & x) const = 0;
                            ^
    src/domain.hpp:26:27: error: ‘array’ is not a member of ‘std’
       std::vector<std::vector<std::array<double, 3>>>
                               ^
    src/domain.hpp:26:27: error: ‘array’ is not a member of ‘std’
    src/domain.hpp:26:49: error: template argument 1 is invalid
       std::vector<std::vector<std::array<double, 3>>>
                                                     ^
    src/domain.hpp:26:49: error: template argument 2 is invalid
    src/domain.hpp:27:18: error: template argument 1 is invalid
       get_features() const
                      ^
    src/domain.hpp:27:18: error: template argument 2 is invalid
    src/domain.hpp:28:3: error: expected unqualified-id before ‘{’ token
       {
       ^
    In file included from /usr/include/CGAL/Uncertain.h:28:0,
                     from /usr/include/CGAL/assertions.h:344,
                     from /usr/include/CGAL/basic.h:42,
                     from /usr/include/CGAL/Cartesian/Cartesian_base.h:28,
                     from /usr/include/CGAL/Simple_cartesian.h:28,
                     from /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28,
                     from src/generate.cpp:5:
    /usr/include/c++/4.8/typeinfo:39:37: error: expected ‘}’ before end of line
     #pragma GCC visibility push(default)
                                         ^
    /usr/include/c++/4.8/typeinfo:39:37: error: expected unqualified-id before end of line
    /usr/include/c++/4.8/typeinfo:39:37: error: expected ‘}’ before end of line
    /usr/include/c++/4.8/typeinfo:39:37: error: expected declaration before end of line
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/bwang31/Software/ENTER/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hijtiy17/pygalmesh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qsf7xh4c-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hijtiy17/pygalmesh/

**Comment by BinWang0213** [comment]
Thanks. It works well now. Is there any possible to use this library in Windows? CGAL seems quite friendly for Visual Studio users.

**Comment by nschloe** [comment]
No idea. If you install CGAL you might get lucky.
