### ISSUE TITLE
Unexpected Error in "generate_mesh()" function:  unexpected keyword argument 'max_cell_circumradius'

### ISSUE THREAD

**Issue by PauloCG33** [nschloe/pygalmesh#125]
Hello!

I'm trying to run some examples I found in the README.md file in a Jupyter Notebook in a Chrome navigator on Windows 10.
The function "generate_mesh()" is not recognizing the input keyword used on the example.
For the pygalmesh installation I used: conda install -c conda-forge pygalmesh

This is the code I'm running:
---------------------------------------------------------------------------
import pygalmesh

s = pygalmesh.Ball([0, 0, 0], 1.0)
mesh = pygalmesh.generate_mesh(s, max_cell_circumradius=0.2)

---------------------------------------------------------------------------

This is the output:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-203d3c7111ea> in <module>
      2 
      3 s = pygalmesh.Ball([0, 0, 0], 1.0)
----> 4 mesh = pygalmesh.generate_mesh(s, max_cell_circumradius=0.2)
      5 

TypeError: generate_mesh() got an unexpected keyword argument 'max_cell_circumradius'

---------------------------------------------------------------------------

I receive similar errors running the other examples.

I'm I missing something? 
Thanks!!
![Untitled](https://user-images.githubusercontent.com/13841846/99427191-db7cab80-28e3-11eb-91a0-1e631aee41e1.png)

**Comment by nschloe** [comment]
You're using an old version.

Also, next time you post an issue please first look at https://guides.github.com/features/mastering-markdown/, especially code blocks via triple fences.

**Comment by AndreEbel** [comment]
Hi, 

First, thanks for this great package. 

Unfortunately, I am also a windows user so I noticed the version availabe for windows on conda was 0.7.2 while the version available for linux and osx is the last one. 

Reading previous issues on the topic, it seems that making pygalmesh available through conda for windows was not so straight forward....

Still, is there any plan to make the last version available on Conda for windows as well in the future ?

**Comment by nschloe** [comment]
That's right, the windows builds are failing (see [here](https://github.com/conda-forge/pygalmesh-feedstock/pull/14/checks)). I have no idea why though and don't have the means to fix them.

> Still, is there any plan to make the last version available on Conda for windows as well in the future ?

Not by me. If someone else steps up, I'll be happy to review PRs, of course.
