### ISSUE TITLE
Problem installing the library from sources

### ISSUE THREAD

**Issue by benoittachet** [nschloe/pygalmesh#127]
Hello,

I've been trying to build this library from its sources, to be able to run the tests and to see how it works, but when I'm running the following commands, I get many errors "no matching function for call to init_radius, init_distance and others.

I'm using Ubuntu 18.04, Python 3.6 and CGAL 5.2. I installed that last one from its sources, as the apt package is not up to date (4.79)

Would you have any idea about this ?

Thank you very much

**Comment by nschloe** [comment]
Dealing with these kind of compile problems is always hard. Before wasting more time, my genuine advice would be to upgrade to ubuntu 20.04+. pygalmesh is available there (https://packages.ubuntu.com/search?keywords=python3-pygalmesh).
