### ISSUE TITLE
Conda (W10)  error due meshing - TIME_LIMIT_REACHED

### ISSUE THREAD

**Issue by Fikus91** [nschloe/pygalmesh#128]
Hi,
I start learning with pygalmesh, but no matter what example(2D/3D) i use, a reach this error:

_Exuding return code: TIME_LIMIT_REACHED_

I'm working with W10ProN/Anaconda Env/VS Code. 
Dual Xeon 2x6c/96GB RAM [HP Workstation]

My pygalmesh version is **0.7.2**, due to problems with pip install newest version ( was pointed here, to use previous release in conda install, also I take examples from 0.7.2 release info)

I'll be grateful if we could find solution for this :)

regards,
Grzegorz

**Comment by ConnorM17** [comment]
I've just started using this repo but I think that means it has "finished" the exuding step. With the created mesh you can call;

mesh.write("filename.vtk") 

and then open it (I used paraview on Ubuntu) to view the created mesh.

**Comment by Fikus91** [comment]
After a few minutes, VTK file  shows in folder , so i guess its end this case.

(i got lot of problem with installing pygalmesh on WSl2 Ubuntu 18, but its another story)

Thanks
