### ISSUE TITLE
Where is the exuding time limit set?

### ISSUE THREAD

**Issue by truenicoco** [nschloe/pygalmesh#136]
First of all, thanks for this great project which makes CGAL usable for C++ allergic people like me.

Using `generate_from_array`, the exuding phase of the mesh optimization process always stops because of `TIME_LIMIT_REACHED`, outputting a mesh with slivers. I don't mind letting it run as long as possible, so is there a simple way to set this limit higher? I am trying to find my way through CGAL's docs and code, but it is not easy…

**Comment by nschloe** [comment]
No idea either. Let me know when you find anything. (Their mailing lists and bug trackers are usually very responsive.)

**Comment by nschloe** [comment]
It's all exposed now via `exude_time_limit` and `exude_sliver_bound`.
