### ISSUE TITLE
Add spline smoothing to volume mesh

### ISSUE THREAD

**Issue by lucascbarbosa** [nschloe/pygalmesh#152]
I'm using `generate_volume_mesh_from_surface_mesh()` to convert a stl surface mesh to a .vtk volume tet mesh. But unfortunetely, I'm having issues with stress concentration in the edges of the elements, so I'm trying to use some kind of spline interpolation to smoothen the elements' edges. 

I have a hunt that this can be made by changing the parameter `cell_radius_edge_ratio` but I'm not sure

**Comment by nschloe** [comment]
No idea. Best get back to the CGAL folks, they are usually quick to reply. https://www.cgal.org/mailing_list.html

**Comment by lucascbarbosa** [comment]
Thx @nschloe! I sent an email regarding that question... Meanwhile, I found that this is possible only in tet10 elements... They are supported by pygalmesh?

**Comment by nschloe** [comment]
Not sure now. How would you enable it in CGAl itself?

**Comment by nschloe** [comment]
Closing for lack of response.
