### ISSUE TITLE
How to use optimesh to improve the result of pygalmesh?

### ISSUE THREAD

**Issue by r03ert0** [nschloe/pygalmesh#166]
Hello,
I'm generating a mesh from a polygon like this:

```python
mesh = pygalmesh.generate_2d(
    contour,
    eds,
    max_edge_size=100,
    num_lloyd_steps=20,
)
```
I can get the vertices and triangles of the mesh using
```python
verts, tris = mesh.points, mesh.cells[0][1]
```

How should I format the data to be able to use `optimesh`? I though I could just feed the `points` and `cells` objects:

```python
result = optimesh.optimize_points_cells(mesh.points, mesh.cells, "CVT (block-diagonal)", 1.0e-5, 100)
```

...but that throws an error:
```
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by nschloe** [comment]
Closing for lack of response.
