### ISSUE TITLE
Issue with remesh

### ISSUE THREAD

**Issue by lucascbarbosa** [nschloe/pygalmesh#168]
Hello Nico, I'm having trouble trying to work with `pygalmesh.remesh_surface`. I have a dirty 2D .stl, which I want to remesh to clean it removing any non manifold and then export to a .vtk. The error and the file is below:
```
CGAL::Polyhedron_incremental_builder_3<HDS>::
lookup_halfedge(): input error: facet  38 shares a halfedge from vertex
CGAL::Polyhedron_incremental_builder_3<HDS>::44 to vertex
lookup_halfedge(): input error: facet 3873 with facet  shares a halfedge from vertex 36.
79 to vertex
58Polyhedron_scan_OFF<Traits>::
operator()(): input error: facet 39 has fewer than 3 vertices.
 with facet 71.

Polyhedron_scan_OFF<Traits>::
operator()(): input error: facet 74 has fewer than 3 vertices.
```
[porosity_0.5273_theta_0.stl.zip](https://github.com/nschloe/pygalmesh/files/7447302/porosity_0.5273_theta_0.stl.zip)

**Comment by nschloe** [comment]
Probably mean CGAL can't work with this file?

**Comment by lucascbarbosa** [comment]
Ok, so I will focus on the mesh, thanks.
