### ISSUE TITLE
test_rectangle mesh.points.shape assert error on i386

### ISSUE THREAD

**Issue by drew-parsons** [nschloe/pygalmesh#170]
test_rectangle (test_2d.py) v 0.10.5 is failing on i386:
```
 ________________________________ test_rectangle ________________________________

    def test_rectangle():
        points = np.array([[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]])
        constraints = [[0, 1], [1, 2], [2, 3], [3, 0]]
    
        mesh = pygalmesh.generate_2d(
            points, constraints, max_edge_size=1.0e-1, num_lloyd_steps=10
        )
    
>       assert mesh.points.shape == (276, 2)
E       assert (279, 2) == (276, 2)
E         At index 0 diff: 279 != 276
E         Use -v to get the full diff

tests/test_2d.py:15: AssertionError
```
see https://ci.debian.net/data/autopkgtest/testing/i386/p/pygalmesh/16320607/log.gz

Pygalmesh 0.9.1 passes the test with the same version of CGAL (5.3), see https://ci.debian.net/data/autopkgtest/testing/i386/p/pygalmesh/16336688/log.gz
The difference might have happened at build time since CGAL is header-only: pygalmesh 0.9.1 was built against CGAL 5.1.1.  Maybe it's a regression between CGAL 5.1.1 and 5.3.

**Comment by nschloe** [comment]
> Maybe it's a regression between CGAL 5.1.1 and 5.3.

Yeah, most likely. I'll accept pull requests fixing this, but I won't be able to invest any time debugging this. Closing.
