### ISSUE TITLE
Help with Difference

### ISSUE THREAD

**Issue by lucascbarbosa** [nschloe/pygalmesh#177]
I'd like to apply a difference operation between two square meshes, but for that I need to extract the domain from these meshes? What is the best way to do this?

**Comment by nschloe** [comment]
> I'd like to apply a difference operation between two square meshes, but for that I need to extract the domain from these meshes? What is the best way to do this?

Perhaps try and extract a polygon from the mesh, then remesh? Anyway, this a problem outside of meshing itself.

**Comment by lucascbarbosa** [comment]
I tried to apply difference with to polygons from pygalmesh.Polygon2D but it is not supported. It demands the domain object...

**Comment by nschloe** [comment]
Yeah 2D support is limited in CGAL, and hence pygalmesh.

**Comment by lucascbarbosa** [comment]
Understood, thank you very much! I managed to get it done via dmsh, but it takes much time. Anyway, thx!
