### ISSUE TITLE
Maximum boundary size?

### ISSUE THREAD

**Issue by lucascbarbosa** [nschloe/pygalmesh#178]
I'm using `generate_2d` to convert an array to a geometry where every element of the array is a "pixel" square, but I'm having a problem: where the element is "0" there should be a square void. However, as this void is surrounded by a closed square boundary, the algorithm fills this space. Is it possible to set a maximum size to the boundary to the algorithm to fill? I can set it to be smaller than the square edge and then this group of void squares will remain void. I don't know if I managed to make myself clear...

**Comment by nschloe** [comment]
Nope, not possible. You might want to look at pygmsh and `holes`, but in any case you'll have to specify them as such.
