### ISSUE TITLE
Parallel build

### ISSUE THREAD

**Issue by lahwaacz** [nschloe/pygalmesh#179]
Running `python setup.py build` calls the gcc commands sequentially which is pretty slow. Is it possible to enable a parallel build? Using cmake & make/ninja this would be trivial, but I have no idea how it's supposed to be done with setuptools...

**Comment by nschloe** [comment]
See [here](https://stackoverflow.com/q/26228136/353337). (Also, [don't use `setup.py` as a command-line tool.](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html))

**Comment by lahwaacz** [comment]
OK, thanks.
