### ISSUE TITLE
test TypeError: 'Mesh' object is not iterable

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#18]
pygalmesh is incoming to Debian, https://salsa.debian.org/science-team/pygalmesh

But there is a problem with the pygalmesh test:

pygalmesh/test$
 python3 test_pygalmesh.py 
Traceback (most recent call last):
  File "test_pygalmesh.py", line 773, in <module>
    test_sphere()
  File "test_pygalmesh.py", line 741, in test_sphere
    vertices, cells, _, _, _ = meshio.read('out.off')
TypeError: 'Mesh' object is not iterable

**Comment by nschloe** [comment]
> pygalmesh is incoming to Debian, salsa.debian.org/science-team/pygalmesh

Nice!

> But there is a problem with the pygalmesh test:

Was fixed in master, just bumped to 0.2.6. Note that all tests are executed only with `pytest` though.

**Comment by RizzerOnGitHub** [comment]
thank nico, works fine now
