### ISSUE TITLE
Release archives do not contain git-lfs files

### ISSUE THREAD

**Issue by lahwaacz** [nschloe/pygalmesh#180]
The [release archives](https://github.com/nschloe/pygalmesh/releases/tag/v0.10.6) do not contain the correct `elephant.vtu` and `sphere.inr` files that are tracked by git-lfs in the repo. The archives contain just text files such as
```
version https://git-lfs.github.com/spec/v1
oid sha256:a11aa572d612abfacace9a31c0e20c8a628bf4ffd50b1661e14790ae02c93b7b
size 135923
```
The correct data should be added to the archives, otherwise it is not possible to run tests on a release (e.g. when building a package for a Linux distribution).

**Comment by nschloe** [comment]
Fixed in the next release.
