### ISSUE TITLE
support for periodic geometries

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#23]
If I understood correctly, pygalmesh currently does not support periodic domains.

I've been generating a periodic geometry using CGAL in C++. That works well enough, but it would be interesting to compare it (whether by quality of mesh, or ease of coding) against a periodic mesh generated by pygalmesh.

**Comment by nschloe** [comment]
How does it work in c++?

**Comment by RizzerOnGitHub** [comment]
I'm no CGAL expert, possibly I've missed some subtleties, but as far as I can see it's a trivial variation.

Use `Periodic_mesh_domain` instead of `Mesh_domain`,
`Periodic_mesh_criteria` instead of `Mesh_criteria`
and generate a `C3t3` mesh (for a 3D example) using `CGAL:: make_periodic_3_mesh_3` instead of `CGAL::make_mesh_3<C3t3>`

I got these classes and functions from the examples at 
https://doc.cgal.org/latest/Periodic_3_mesh_3/Periodic_3_mesh_3_2mesh_implicit_shape_8cpp-example.html
or
https://doc.cgal.org/latest/Periodic_3_mesh_3/index.html#Periodic_3_mesh_33DDomainsImplicitIsosurfaces

**Comment by nschloe** [comment]
So I played around with that and found that CGAL 4.13 will only segfault, even for their own examples. Let's wait for 4.14 and cross our fingers?

**Comment by RizzerOnGitHub** [comment]
That's annoying.  Do they still segfault if you use cmake to build with CMakeFiles.txt for the c++ code generated using cgal_create_cmake_script (or cgal_create_CMakeLists) ?

**Comment by nschloe** [comment]
Haven't tried those, but, well, the error is not in building the executable, but when running it. That's why I don't think the build process needs fixing.

**Comment by RizzerOnGitHub** [comment]
Do they segfault with a cmake build using CMakeLists.txt generated by cgal_create_cmake_script (if not cgal_create_CMakeLists)?   The example works successfully for me with CGAL 4.13-1+b2.

**Comment by nschloe** [comment]
Can you please post your files so I can try it out?

**Comment by RizzerOnGitHub** [comment]
It's just a copy&paste of the cpp file at https://doc.cgal.org/latest/Periodic_3_mesh_3/Periodic_3_mesh_3_2mesh_implicit_shape_8cpp-example.html

**Comment by nschloe** [comment]
Same here, doesn't work for me. What's your CMakeLists.txt?

**Comment by nschloe** [comment]
Got it now.
![k](https://user-images.githubusercontent.com/181628/55399063-64e23d00-554a-11e9-8003-591800f3314c.png)
Let me try and bisect. God, I "love" C++.

**Comment by RizzerOnGitHub** [comment]
Ah good :)

(I actually do love C++ ;)  But python is faster for prototyping).

**Comment by nschloe** [comment]
Okay, I can't get it to work as a library. Attached is the _compile_ error, perhaps you can give me a hint on what's wrong. I simply have no idea.

[err.log](https://github.com/nschloe/pygalmesh/files/3033758/err.log)

**Comment by nschloe** [comment]
Okay, after switching the compiler to g++, it works. Sheesh. However:
```
Inserting protection balls...
  refine_balls = true
  min_balls_radius = 0
  min_balls_weight = 0
insert_corners() done. Nb of points in triangulation: 0
insert_balls_on_edges() done. Nb of points in triangulation: 0
refine_balls() done. Nb of points in triangulation: 0

construct initial points (nb_points: 12)
12/12 initial point(s) found...
Start surface scan...Scanning triangulation for bad facets (sequential) - number of finite facets = 59...
Number of bad facets: 0
scanning edges (lazy)
scanning vertices (lazy)
end scan. [Bad facets:0]

Refining Surface...
Legend of the following line: (#vertices,#steps,#facets to refine,#tets to refine)
(12,0,0,0)
Total refining surface time: 0.000142097s

Start volume scan...Scanning triangulation for bad cells (sequential)... 26 cells scanned, done.
Number of bad cells: 12
end scan. [Bad tets:12]

Refining...
Legend of the following line: (#vertices,#steps,#facets to refine,#tets to refine)
(21,8,0,69) (37035.8 vertices/s)Segmentation fault (core dumped)
```

**Comment by nschloe** [comment]
Further debugging fails with memory exhausting at compile time:
```
  x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Okay, I'm giving up at this point. Pull requests are welcome.

**Comment by RizzerOnGitHub** [comment]
CGAL is quite the memory hog.  mshr fails to build on some arches because of that. Actually pygalmesh itself fails on some arches, even without the periodic extension.

**Comment by nschloe** [comment]
![C-is-truly-something-else](https://user-images.githubusercontent.com/181628/55437128-705f5380-559e-11e9-825f-49f747c617af.jpg)

**Comment by nschloe** [comment]
Alright, just merged and published as 0.3.1.

**Comment by RizzerOnGitHub** [comment]
Nice. Thanks Nico!

**Comment by nschloe** [comment]
Me completing this PR:

![im](https://user-images.githubusercontent.com/181628/56681063-cff5de00-66c8-11e9-989b-c62d6614c245.png)

The big motivation for completing this was to make sure that no one else has to go through the ordeal ever again. Thanks for bumping it in Debian right away.
