### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by mathieu-barre** [nschloe/pygalmesh#32]
Hello,

I have some trouble with pygalmesh installation. I work on Ubuntu 18.04. I successfully installed CGAL and Eigen, but when I try
```
pip3 install -U pygalmesh
```
I get the [following error message](https://github.com/nschloe/pygalmesh/files/3359326/error-message.txt).

I also tried by cloning the sources and using ```python3 setup.py install``` but I got 
[this error message](https://github.com/nschloe/pygalmesh/files/3359342/error-message-setup.txt).

The CMake installation provided went into the same error.

Finally, I thought that the problem may come from my version of CGAL, so I cloned a [more recent version of CGAL](https://github.com/CGAL/cgal). I added 
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
find_package(CGAL REQUIRED)
include(${CGAL_USE_FILE})
```
to ```CMakeLists.txt``` and did ```cmake -DCGAL_DIR=$HOME/Downloads/cgal```. Then the ```make``` command successfully ended with
```
[100%] Linking CXX shared module pygalmesh.cpython-36m-x86_64-linux-gnu.so
[100%] Built target pygalmesh
```
but when I try ```pytest``` it stills tell me that there is no module named pygalmesh.
(I precise that I have no knowledge in CMake, so this last try is quite experimental)

Do you have any idea where this installation problem could come from ?
Thank you in advance for your help.

**Comment by nschloe** [comment]
Yeah, you'll need a newer version of CGAL (the one in Ubuntu 19.04) or restrict yourself to an older version of pygalmesh.

**Comment by mathieu-barre** [comment]
Thank you very much for your quick answer !
I managed to install an older version of pygalmesh.
