### ISSUE TITLE
error in test_inr.py

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#33]
This 0.3.5 test error in test/test_inr.py is reproducible on Debian with CGAL 4.13-1+b2:

        def test_inr():
            helpers.download("liver.inr", "c69513a79231881942a86df56d41090e")
            mesh = pygalmesh.generate_from_inr("/tmp/liver.inr", cell_size=5.0, verbose=False)
        
            tol = 1.0e-3
            assert abs(max(mesh.points[:, 0]) - 2.385709228515625e02) < tol
            assert abs(min(mesh.points[:, 0]) - 3.307421875000000e01) < tol
            assert abs(max(mesh.points[:, 1]) - 1.947126770019531e02) < tol
            assert abs(min(mesh.points[:, 1]) - 2.314493751525879e01) < tol
            assert abs(max(mesh.points[:, 2]) - 1.957076873779297e02) < tol
            assert abs(min(mesh.points[:, 2]) - 1.365468883514404e01) < tol
         
            vol = sum(helpers.compute_volumes(mesh.points, mesh.cells["tetra"]))
     
        >  assert abs(vol - 1.759106599498153e06) < tol
    
        E       assert 1.9967572691384703 < 0.001
        E        +  where 1.9967572691384703 = abs((1759104.6027408838 - 1759106.599498153))
    
    test/test_inr.py:21: AssertionError

https://ci.debian.net/data/autopkgtest/testing/amd64/p/pygalmesh/2552856/log.gz

**Comment by nschloe** [comment]
Okay, I've released 0.3.6 with a fix for the tolerance test in test_inr. Hopefully it will work now; if not, feel free to increase the tolerance even more via patching.

**Comment by RizzerOnGitHub** [comment]
looking good, thanks Nico.
