### ISSUE TITLE
reading .msh when it contains binary sections.

### ISSUE THREAD

**Issue by goodok** [nschloe/pygalmesh#34]
When reading a .msh file version 4.1, when the file contains a section
in the form of binary lines (for example, $Parametrizations"), an error
occurs when reading them in utf-8 encoding.

Example
file: https://goodok.github.io/data/ellipsoid.msh
```
import meshio

fn = 'ellipsoid.msh'
mesh = meshio.read(fn)
print(mesh)
```

Output

```
/home/.virtualenvs/aaaaa/lib/python3.6/site-packages/meshio/msh_io/msh4_1.py in read_buffer(f, is_ascii, data_size)
     85                 #except UnicodeDecodeError:
     86                 #    pass
---> 87                 line = f.readline().decode("utf-8").strip()
     88 
     89     cell_data = cell_data_from_raw(cells, cell_data_raw)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 16: invalid start byte
```

Versions:
meshio:                 2.3.10
MeshFormat:         4.1 1 8
created by gmsh:   4.4.0
python3.6

**Comment by nschloe** [comment]
Is this for meshio or pygalmesh?

**Comment by goodok** [comment]
The file is created using _pygmesh_ (which in turn uses _gmsh_). _pygmesh_ could not read the result of its work. Аfter debugging, it was found that the bug appears in _meshio_. And now I'm trying to read it with a pure _meshio_ (see the example code on python in the description). After fixing it, I hope _pygmesh_ will read this file too.

**Comment by nschloe** [comment]
Note that this is pyGALmesh, frontend to CGAL, not pygmsh, frontent to gmsh.

**Comment by goodok** [comment]
Yes, sorry (edited).
