### ISSUE TITLE
[Question] Size function/field

### ISSUE THREAD

**Issue by MartinGrignard** [nschloe/pygalmesh#36]
Hi,

First I would like to thank you for this really useful package.

I'm considering to use it in a FEM pipeline to generate multimaterial models based on volume images. To achieve this task, I'm currently using `generate_from_inr()` function.

For now it works like a charm but I'm wondering if it would be possible to prodive it with a size function for the facets size or the cell size. For instance, I have a big smooth area that I know would be ok with a much lower facet size but I still need to use a small value of this parameter to make sure that smaller parts are meshed properly. It would be great to be able to provide a volume image or a function giving the facet size for each voxel of the reference image.

This functionality already exists in CGAL ([3.5.2 Different Sizing Field for Different Subdomains](https://doc.cgal.org/latest/Mesh_3/index.html)) but I don't see anything similar in `pygalmesh`.
Is it possible using your package?

Thanks!

**Comment by nschloe** [comment]
Not possible yet, but definitely a good suggestion. I'll take a look.

**Comment by MartinGrignard** [comment]
Ok, thanks for this quick answer. If you want some help on this, I might try to add it myself.

**Comment by nschloe** [comment]
I'd say I'll do it for the regular mesh generation, you can adapt it for INR from there.

**Comment by nschloe** [comment]
If I still needed a reminder why I _hate_ to work with C++, today was the day.

Okay, so sizing_fields landed for meshes defined by implicit domains. It works, but I'm not too happy with the code. Check out the readme and https://github.com/nschloe/pygalmesh/blob/master/src/generate.cpp#L148.

Perhaps you find some ways to make it more elegant. I'd be great if one could simply pass a function instead of a class member with an `eval` on it. Also the C++ code is so repetetive...

Anyway, have look.

**Comment by MartinGrignard** [comment]
Thanks for this quick integration, I will check how it works because I'm not familiar with CGAL.
Indeed, passing a function directly rather than using a class would be easier.
It looks like [this thread](https://stackoverflow.com/questions/30437932/how-to-pass-python-function-as-an-argument-to-c-function-using-cython) shows a solution for this issue (depending on the amount of work you want to put in this feature).

**Comment by nschloe** [comment]
CGAL 5.0 will clean this up. https://github.com/CGAL/cgal/issues/4146

**Comment by nschloe** [comment]
With the release of CGAL 5 and pygalmesh 0.5.0, this got cleaned up.
