### ISSUE TITLE
 module 'pygalmesh' has no attribute 'generate_surface_mesh'

### ISSUE THREAD

**Issue by chenshenlv** [nschloe/pygalmesh#40]
Hi 
Thanks for this pygalmesh which provide a surface mesh generator for our project. 
I am intend to run the pygalmesh under conda environment, but after I install the pygalmesh through pip/pip3 I can not use the pygalmesh when I edit and compile the code in a IDE, I use spyder. It gives me the error:
```
Traceback (most recent call last):

  File "<ipython-input-1-108614fff67b>", line 1, in <module>
    runfile('/home/jason/CUDA/Pymesh/pygalmesh.py', wdir='/home/jason/CUDA/Pymesh')

  File "/usr/local/anaconda3/envs/pymesh2/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/local/anaconda3/envs/pymesh2/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jason/CUDA/Pymesh/pygalmesh.py", line 8, in <module>
    import pygalmesh

  File "/home/jason/CUDA/Pymesh/pygalmesh.py", line 9, in <module>
    pygalmesh.generate_surface_mesh()

AttributeError: module 'pygalmesh' has no attribute 'generate_surface_mesh'`
```
Seems every attribute under pygalmesh can not be used like Ball, generate_mesh. etc.
Then I build the pygalmesh from the source and run the pytest, it returns several error:
```
ImportError while importing test module '/home/jason/Downloads/pygalmesh-0.4.0/test/test_periodic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
pygalmesh-0.4.0/test/test_periodic.py:3: in <module>
    import pygalmesh
/usr/local/anaconda3/envs/pymesh2/lib/python3.6/site-packages/pygalmesh/__init__.py:4: in <module>
    from _pygalmesh import (
E   ImportError: /usr/local/anaconda3/envs/pymesh2/lib/python3.6/site-packages/_pygalmesh.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4CGAL7Image_312private_readEP11point_imageNS0_3OwnE
```
Seems it has some problem to import pygalmesh properly.
I tried different version of pygalmesh from version 0.4.0 to 0.3.0, they all give this error. would you please give me some advice.

thanks

**Comment by nschloe** [comment]
> AttributeError: module 'pygalmesh' has no attribute 'generate_surface_mesh'`

Looks like an installation failure.

**Comment by chenshenlv** [comment]
Yes, it is a installation problem, haven't find a solution, but thanks for introducing the basic library used in your program -cgal. After doing some research, I write some code for my project using the cgal. 
Thanks so much, will find the solutions to the faulty installation and give a reply hope this can help others.

**Comment by nschloe** [comment]
Closing. Feel free to reopen at any time.
