### ISSUE TITLE
Problem installing pygalmesh 0.4.0

### ISSUE THREAD

**Issue by antko** [nschloe/pygalmesh#45]
I face a persistent issue while trying to install `pygalmesh 0.4.0` on Google Colabs, with `libcgal-dev:amd64 (4.11-2build1)` and `libeigen3-dev (3.3.4-4)` installed.
The full log of the installation failure is here :
https://colab.research.google.com/drive/1URJt2v-k73DpVqXj3n-_5mU5tilBZWNp
As a side note, I have the same issue on my Mac (macOS Mojave).
It looks like the root of the problem is in the interface with CGAL -- but this is clearly beyond my debugging abilities.
Any idea of how to correctly install pyglamesh in these environments?

**Comment by nschloe** [comment]
You need a newer version of CGAL.
