### ISSUE TITLE
building with CGAL 5

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#56]
pygalmesh needs some help to build against CGAL 5, which is now header-only. 

Dropping the CGAL libraries themselves is easy enough.  (I guess you'd want the build able to work with both CGAL 4 or 5)

But then there's a more subtle problem (on Debian unstable).  setup.py seems to be invoking gcc to compile the extensions, but the files are C++.  setup.py does refer to C++, but nevertheless the build proceeds with x86_64-linux-gnu-gcc instead of x86_64-linux-gnu-g++.

Consequently when running tests,

       dh_auto_test -O--buildsystem=pybuild
    I: pybuild base:217: cd /home/projects/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build; python3.8 -m unittest discover -v 
    pygalmesh (unittest.loader._FailedTest) ... ERROR
    
    ======================================================================
    ERROR: pygalmesh (unittest.loader._FailedTest)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: pygalmesh
    Traceback (most recent call last):
      File "/usr/lib/python3.8/unittest/loader.py", line 470, in _find_test_path
        package = self._get_module_from_name(name)
      File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
        __import__(name)
      File "/home/projects/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build/pygalmesh/__init__.py", line 2, in <module>
        from _pygalmesh import (
    ImportError: /home/projects/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build/_pygalmesh.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE

The missing symbol is in `libstdc++.so`.

**Comment by RizzerOnGitHub** [comment]
Joachim Reichel suggests it needs
`libraries=["stdc++", "gmp", "mpfr"]`

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946234

**Comment by RizzerOnGitHub** [comment]
The relationship between cmake and setup.py seems to complicate the build conditions.

Joachim says the mere presence of cmake means it is invoked in pybuild build, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946233.

But it doesn't work that way for me.  For me it's either `dh --buildsystem=pybuild` which does not invoke cmake, or  `dh --buildsystem=cmake`, not clear what that does to the python build.

**Comment by nschloe** [comment]
This seems like it's related to https://github.com/pypa/setuptools/issues/1732#issuecomment-548307702: setuptools indeed uses the C compiler, not C++, to compile C++ projects. Only the linker step uses `CXX`. Does it not on Debian?

**Comment by nschloe** [comment]
> The relationship between cmake and setup.py seems to complicate the build conditions.

Hm. Well, the CMake files aren't _terribly_ important to me, but sometimes I use them to debug which is why I don't want to toss them completely. If we can find another way of making this work, that'd be great.

**Comment by RizzerOnGitHub** [comment]
If we're clear on the intended role of cmake (intended for developer debugging only) then we can just ignore them.  Perhaps a comment could be added to CMakeLists.txt or README to make that clear

The failing CGAL 5 build is documented at https://buildd.debian.org/status/package.php?p=pygalmesh
 x86_64-linux-gnu-gcc is used for the linking step.  This is with python3.8, so it could be possible that setuptools needs to be updated for the python3.8 context.

**Comment by nschloe** [comment]
Fixing this right now.

**Comment by nschloe** [comment]
Alright, all done now.

**Comment by RizzerOnGitHub** [comment]
Thanks, will test.
