### ISSUE TITLE
Force the use of system installed CGAL instead of user installed?

### ISSUE THREAD

**Issue by swiss-knight** [nschloe/pygalmesh#59]
Hello,

While installing the package with `pip`, I run into many (many!) errors and I noticed that to build the wheel, it was the `/usr/local` folder that was search for CGAL libraries.    

And indeed, I installed some CGAL stuff there while I was trying to compile it from sources a time ago.    

In between, I also installed the CGAL libraries using `apt`, namely these;

```
libcgal-demo - C++ library for computational geometry (demos)
libcgal-dev - C++ library for computational geometry (development files)
libcgal-qt5-13 - C++ library for computational geometry (support for Qt5)
libcgal-qt5-dev - C++ library for computational geometry (development files, support for Qt5)
libcgal13 - C++ library for computational geometry
cgal - cgal-4.13-latest
```

I want now to tell `pip` to install `pygalmesh` using the libraries installed by `apt` in `/usr/lib` instead of the ones found in `/usr/local/lib`.        

Is this possible?    

### Environment:    
I'm on Ubuntu 18.04 64bit: `5.3.0-26-generic x86_64 GNU/Linux`     
My python is: `Python 3.6.9 (default, Nov  7 2019, 10:44:02)`      
And pygalmesh found by pip is:  `pygalmesh (0.5.0)  - Python frontend to CGAL's 3D mesh generation capabilities`    
   

Thanks.

**Comment by nschloe** [comment]
pygalmesh compiles the sources without any special treatment, so perhaps you can use environment variables to tweak this. I don't know exactly how to do it, but since this problem is not specific to pygalmesh, you should be able to find plenty of information online.

If I were you, I'd probably just get rid of the installation in `/usr/local/`.

**Comment by swiss-knight** [comment]
### Update    

Just to let you know; installation of `pygalmesh` using `pip` succeeded after having build the CGAL 5.0.0 release from sources along with the cgal-swig-bindings (CGAL 5.0 release), both available at https://github.com/CGAL as pinned repositories (as of 2020.01.31). 

I think I only missed the bindings previously.        
Hope it may help some people passing by.
