### ISSUE TITLE
test_inr.py now fails

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#60]
test_inr.py has recently started failing in Debian tests:

        def test_inr():
            this_dir = os.path.dirname(os.path.abspath(__file__))
            mesh = pygalmesh.generate_from_inr(
                os.path.join(this_dir, "meshes", "skull_2.9.inr"), cell_size=5.0, verbose=False
            )
        
            tol = 2.0e-3
            ref = [2.031053e02, 3.739508e01, 2.425594e02, 2.558910e01, 2.300883e02, 1.775010e00]
            assert abs(max(mesh.points[:, 0]) - ref[0]) < tol * ref[0]
            assert abs(min(mesh.points[:, 0]) - ref[1]) < tol * ref[1]
            assert abs(max(mesh.points[:, 1]) - ref[2]) < tol * ref[2]
            assert abs(min(mesh.points[:, 1]) - ref[3]) < tol * ref[3]
            assert abs(max(mesh.points[:, 2]) - ref[4]) < tol * ref[4]
    >       assert abs(min(mesh.points[:, 2]) - ref[5]) < tol * ref[5]
    E       assert 0.0294994218444824 < (0.002 * 1.77501)
    E        +  where 0.0294994218444824 = abs((1.7455106 - 1.77501))
    E        +    where 1.7455106 = min(array([115.045494, 116.24661 , 122.3319  , ...,  63.492596, 101.66734 ,\n       169.07079 ], dtype=float32))
    
    test/test_inr.py:20: AssertionError

see https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pygalmesh/4327742/log.gz
https://ci.debian.net/packages/p/pygalmesh/unstable/amd64/

It's the same version of pygalmesh as used when the same test passed previously. Not clear what has changed to trigger the failure now.

**Comment by nschloe** [comment]
I'll check it out.

**Comment by nschloe** [comment]
Okay, I've released 0.5.1 with a "fix" (just relaxed the tolerance). You do need meshio 4.0.2 for this though. You could also just relax the test tolerance to `2.0e-2` yourself.
