### ISSUE TITLE
Is it possible to perform difference on volume meshes?

### ISSUE THREAD

**Issue by heidtn** [nschloe/pygalmesh#75]
I noticed that the boolean functionality only works on primitives.  Is it possible to perform a difference on arbitrary volume meshes (specifically imported and converted STL files)?  My main target is testing fully encapsulated inclusions, but I has of yet been unable to find a package that can support this. 

My hope was to be able to aquire 2 meshes via pygalmesh.generate_volume_mesh_from_surface_mesh, and perform a boolean difference on them, but these objects aren't supported for boolean differences.  Any pointers here would be greatly appreciated.

**Comment by nschloe** [comment]
> Is it possible to perform a difference on arbitrary volume meshes (specifically imported and converted STL files)?

No. pygalmesh creates a mesh from a geometry. It's not possible to feed meshes into pygalmesh (unless for creating a volume mesh from a surface mesh).
