### ISSUE TITLE
Git Actions CI

### ISSUE THREAD

**Issue by uvilla** [nschloe/pygalmesh#77]
I was comparing the difference in the CI scripts for `Github Actions` and `CircleCi`.

Shouldn't [line 33 of `/.github/workflows/ci.yml`](https://github.com/nschloe/pygalmesh/blob/455d2385a5ef99b9ec45c65708fd819f845ff50e/.github/workflows/ci.yml#L33) read
```
        sudo apt-get install -y libeigen3-dev python3-pip clang
```

rather then

```
        sudo apt-get install -y libcgal-dev libeigen3-dev python3-pip clang
```

**Comment by nschloe** [comment]
gh-actions won't work b/c they need a newer CGAL anyway. Waiting for gh to update their images.
