### ISSUE TITLE
add LICENCE to sdist

### ISSUE THREAD

**Issue by flothesof** [nschloe/pygalmesh#82]
As has been notified in https://github.com/conda-forge/staged-recipes/pull/11457, it seems that the pygalmesh sdist uploaded to pypi does not contain the LICENCE file. Would it be possible to include it so that the conda-forge build satisfies their standards?

A possible way to achieve this would be to modify `setup.cfg` like so ([source](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)):
```
[metadata]
long_description = file: README.md, LICENSE
```
If @nschloe is ok, I can propose a PR to do that.
Best regards,

Florian

**Comment by nschloe** [comment]
Definitely.
