### ISSUE TITLE
Github Workflow build is broken

### ISSUE THREAD

**Issue by nehaljwani** [nschloe/pygalmesh#87]
ubuntu-latest virtual env is based off of 18.04 and the latest version of boost available there is 1.65.1, and boost is an interface dependency for libcgal v5 : https://github.com/CGAL/releases/blob/CGAL-5.0.2/include/CGAL/Mesh_3/Is_mesh_domain_field_3.h#L32-L55

The solution is to either somehow install and use boost 1.66.0+ or fix pygalmesh to add compatibility for boost 1.65.1

**Comment by nschloe** [comment]
That is true, and won't fix before GitHub updates their images. Perhaps 20.04 is in line. Let's close this since it's not actually actionable.
