### ISSUE TITLE
importlib dependency not taken properly into account (windows)

### ISSUE THREAD

**Issue by flothesof** [nschloe/pygalmesh#92]
Following yesterday's work regarding conda-forge builds, I tried out the newly added build on windows this morning.
Here's what I did:
```
conda create -n test_pygalmesh python=3.7
conda activate test_pygalmesh
conda install -c conda-forge pygalmesh
```
This works well. I then do `python -c "import pygalmesh"` which raises an error:
```python_traceback
(test_pygalmesh) C:\>python -c "import pygalmesh"
Traceback (most recent call last):
  File "C:\Anaconda3\envs\test_pygalmesh\lib\site-packages\pygalmesh\__about__.py", line 3, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (C:\Anaconda3\envs\test_pygalmesh\lib\importlib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\test_pygalmesh\lib\site-packages\pygalmesh\__init__.py", line 25, in <module>
    from .__about__ import __version__
  File "C:\Anaconda3\envs\test_pygalmesh\lib\site-packages\pygalmesh\__about__.py", line 5, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```
When checking for the existence of a module called `importlib_metadata`, I cannot find any.

Doing `pip install importlib-metadata` fixes the issue. Notice that the pip install requires a hyphen instead of an underscore when installing. Could that be the reason?

**Comment by nschloe** [comment]
It's this library: https://pypi.org/project/importlib-metadata/

**Comment by flothesof** [comment]
I checked the [recipe.yaml](https://github.com/conda-forge/pygalmesh-feedstock/blob/master/recipe/meta.yaml) again and noticed we haven't specified importlib_metadata explicitly as a dependency for running (only python and meshio). However, the CI build still installs it [see this log for example](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/154187/logs/70) but it installs both with a hyphen and an underscore, which seems weird to me. After checking, it turns out that one of the builds has been archived (see https://github.com/conda-forge/importlib-metadata-feedstock/issues/2).

**Comment by nehaljwani** [comment]
Yes, we should add `importlib-metadata` to the run deps, according to: 
https://github.com/nschloe/pygalmesh/blob/master/setup.cfg#L30

We should also add these [entry points](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#python-entry-points):
```
    pygalmesh-volume-from-surface = pygalmesh._cli:volume_from_surface
    pygalmesh-remesh-surface = pygalmesh._cli:remesh_surface
    pygalmesh-from-inr = pygalmesh._cli:inr
```

**Comment by nehaljwani** [comment]
Unfortunately, conda differentiates between '-' and '_'.
I had opened an issue long time ago: https://github.com/conda/conda/issues/6762 but nothing has happened yet.

**Comment by nehaljwani** [comment]
While we are at it, we should also update the constrains on meshio accordingly.

**Comment by nehaljwani** [comment]
As for your other query regarding the double entry in the build log, that's because of: https://github.com/conda-forge/importlib_metadata-feedstock/blob/df6c8e71fa501b866c663d15637da2824ee41f1d/recipe/meta.yaml#L37-L45

It's harmless. One is just a dependency on the other (as a meta package, no contents)

**Comment by flothesof** [comment]
Still not working with the new build on my windows. 

I think I forgot two things in the PR checklist: bumping version number and asking for a re-render. I'll try it now.

**Comment by flothesof** [comment]
made this new PR and merged it to test again. https://github.com/conda-forge/pygalmesh-feedstock/pull/4

**Comment by flothesof** [comment]
This now works in the scenario outlined above. Closing, feel free to reopen if I missed something.
