### ISSUE TITLE
Error when generating surface mesh from custom superellipsoid function

### ISSUE THREAD

**Issue by eleramp** [nschloe/pygalmesh#94]
Hi, I'm trying to generate a surface mesh from a superellipsoid function:

```python
import pygalmesh
import meshio

class SQ(pygalmesh.DomainBase):
    def __init__(self):
        super().__init__()

    def eval(self, x):
        l4 = 0.5
        l5 = 0.5
        return (x[0]**(2./l5) + x[1]**(2./l5))**(l5/l4) + x[2]**(2./l4) - 1

    def get_bounding_sphere_squared_radius(self):
        return 10

d = SQ()

mesh = pygalmesh.generate_surface_mesh(
    d,
    angle_bound=10,
    radius_bound=0.1,
    distance_bound=0.1
)

meshio.write("out.obj", mesh)
```

By varying the parameters `l4` and `l5` between 0.1 and 2, the shape of the superellipsoid should vary according to the following image:
<img src="https://user-images.githubusercontent.com/26541436/82320451-97abf680-99d3-11ea-82a5-d7c928c997e5.png" width=300>

By using values in `[0.1,1]` everything works perfectly and I can generate correct surface meshes.

However, if I use values `>1` I get the following error:

```bash
line 160, in generate_surface_mesh
    _generate_surface_mesh(
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

Do you see the reason for this?

Thank you for your work!

**Comment by nschloe** [comment]
Your `out` is complex-valued in this case.

**Comment by nschloe** [comment]
You might want `(x[0] ** 2) ** (1/l5)`.

**Comment by eleramp** [comment]
Ah yes, I see. It works now thank you!
