### ISSUE TITLE
Installation and running tests

### ISSUE THREAD

**Issue by nicolacavallini** [nschloe/pygalmesh#95]
Hi all,

installed cgal from ubuntu distro, with:
```
sudo apt install libcgal-dev
```
An I got this error while compiling `pygalmesh`:
```
/usr/include/CGAL/internal/boost/array_binary_tree.hpp:54:28: error: expected template-name before ‘<’ token
         : ::boost::iterator<std::forward_iterator_tag,
```
I downloaded, compiled, and installed successfully cgal. 
I can now compile `pygalmesh` with:
```
 cmake -DCGAL_DIR=/home/nicola/local/usr/cgal/ -DCMAKE_BUILD_TYPE=Release ..
```
I go back to the top level `pygalmesh`, and run `pytest` and I get this:
```
ModuleNotFoundError: No module named '_pygalmesh'
```
I know I am missing some path, but I cannot figure out which one. 

Thanks a lot.

**Comment by nschloe** [comment]
Just install pygalmesh from ubuntu. https://packages.ubuntu.com/search?keywords=python3-pygalmesh

**Comment by nicolacavallini** [comment]
Unfortunately that didn't work, same error.

I started from a clean conda environment, dedicated to pygalmesh. 
`conda` installed pygalmesh then the other dependencies, now it is working.

**Comment by nschloe** [comment]
If you installed it from Ubuntu and you still get an error, it's some weird config error on your machine.
