### ISSUE TITLE
Repeatable Meshes

### ISSUE THREAD

**Issue by ManyAngledOne** [nschloe/pygalmesh#99]
Each time pygalmesh creates a mesh, that mesh is unique. This can make things difficult if it is used to generate meshes in, for example, an automated testing environment.

CGAL supports setting its initial seed:
https://github.com/CGAL/cgal/issues/4376

If this property was controllable in pygalmesh one could ensure the meshes generated were identical.

Currently the workaround is just to generate a mesh and save it with meshio.

**Comment by nschloe** [comment]
Fixed in #100.
